name: kuller
description: "Kuller — эстонский язык для курьеров: симулятор доставки еды."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.0
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
