/// Словарь лемм для грамматического разбора слов в текстах.
///
/// kind: 'n' — существительное (nimetav/omastav/osastav),
///       'a' — прилагательное/числительное (те же 3 формы),
///       'v' — глагол (ma-инфинитив / da-инфинитив / основа настоящего),
///       'p' — послелог, 'x' — служебное слово (без разбора форм).
class Lexeme {
  final String kind;
  final String f1;
  final String f2;
  final String f3;
  final String tr; // украинский перевод
  final String pl; // mitmuse osastav (частичный падеж мн.ч.), если нужен
  const Lexeme(this.kind, this.f1, this.f2, this.f3, this.tr, [this.pl = '']);
}

const List<Lexeme> lexicon = [
  // ---------------- Дом и комнаты ----------------
  Lexeme('n', 'tuba', 'toa', 'tuba', 'кімната', 'tube'),
  Lexeme('n', 'maja', 'maja', 'maja', 'будинок'),
  Lexeme('n', 'korter', 'korteri', 'korterit', 'квартира'),
  Lexeme('n', 'kelder', 'keldri', 'keldrit', 'підвал'),
  Lexeme('n', 'köök', 'köögi', 'kööki', 'кухня'),
  Lexeme('n', 'kööginurk', 'kööginurga', 'kööginurka', 'кухонний куток'),
  Lexeme('n', 'esik', 'esiku', 'esikut', 'передпокій'),
  Lexeme('n', 'vannituba', 'vannitoa', 'vannituba', 'ванна кімната'),
  Lexeme('n', 'magamistuba', 'magamistoa', 'magamistuba', 'спальня'),
  Lexeme('n', 'elutuba', 'elutoa', 'elutuba', 'вітальня'),
  Lexeme('n', 'töötuba', 'töötoa', 'töötuba', 'робоча кімната'),
  Lexeme('n', 'lastetuba', 'lastetoa', 'lastetuba', 'дитяча кімната'),
  Lexeme('n', 'sahver', 'sahvri', 'sahvrit', 'комора'),
  Lexeme('n', 'hoiuruum', 'hoiuruumi', 'hoiuruumi', 'комора, підсобка'),
  Lexeme('n', 'rõdu', 'rõdu', 'rõdu', 'балкон'),
  Lexeme('n', 'terrass', 'terrassi', 'terrassi', 'тераса'),
  Lexeme('n', 'aed', 'aia', 'aeda', 'сад'),
  Lexeme('n', 'aken', 'akna', 'akent', 'вікно'),
  Lexeme('n', 'uks', 'ukse', 'ust', 'двері'),
  Lexeme('n', 'sein', 'seina', 'seina', 'стіна'),
  Lexeme('n', 'põrand', 'põranda', 'põrandat', 'підлога'),
  Lexeme('n', 'katus', 'katuse', 'katust', 'дах'),
  Lexeme('n', 'lamekatus', 'lamekatuse', 'lamekatust', 'плаский дах'),
  Lexeme('n', 'korrus', 'korruse', 'korrust', 'поверх'),
  Lexeme('n', 'lift', 'lifti', 'lifti', 'ліфт'),
  Lexeme('n', 'koridor', 'koridori', 'koridori', 'коридор'),
  Lexeme('n', 'sissepääs', 'sissepääsu', 'sissepääsu', 'вхід'),
  Lexeme('n', 'nurk', 'nurga', 'nurka', 'куток'),
  Lexeme('n', 'kodu', 'kodu', 'kodu', 'дім, домівка'),
  Lexeme('n', 'garaaž', 'garaaži', 'garaaži', 'гараж'),
  Lexeme('n', 'trepp', 'trepi', 'treppi', 'сходи'),
  // ---------------- Мебель и вещи ----------------
  Lexeme('n', 'diivan', 'diivani', 'diivanit', 'диван'),
  Lexeme('n', 'nurgadiivan', 'nurgadiivani', 'nurgadiivanit', 'кутовий диван'),
  Lexeme('n', 'laud', 'laua', 'lauda', 'стіл'),
  Lexeme('n', 'kirjutuslaud', 'kirjutuslaua', 'kirjutuslauda', 'письмовий стіл'),
  Lexeme('n', 'töölaud', 'töölaua', 'töölauda', 'робочий стіл'),
  Lexeme('n', 'kohvilaud', 'kohvilaua', 'kohvilauda', 'журнальний столик'),
  Lexeme('n', 'söögilaud', 'söögilaua', 'söögilauda', 'обідній стіл'),
  Lexeme('n', 'köögilaud', 'köögilaua', 'köögilauda', 'кухонний стіл'),
  Lexeme('n', 'tool', 'tooli', 'tooli', 'стілець', 'toole'),
  Lexeme('n', 'taburet', 'tabureti', 'taburetti', 'табурет'),
  Lexeme('n', 'voodi', 'voodi', 'voodit', 'ліжко'),
  Lexeme('n', 'kapp', 'kapi', 'kappi', 'шафа'),
  Lexeme('n', 'riidekapp', 'riidekapi', 'riidekappi', 'шафа для одягу'),
  Lexeme('n', 'raamatukapp', 'raamatukapi', 'raamatukappi', 'книжкова шафа'),
  Lexeme('n', 'köögikapp', 'köögikapi', 'köögikappi', 'кухонна шафа'),
  Lexeme('n', 'riiul', 'riiuli', 'riiulit', 'полиця', 'riiuleid'),
  Lexeme('n', 'raamaturiiul', 'raamaturiiuli', 'raamaturiiulit', 'книжкова полиця'),
  Lexeme('n', 'jalanõuderiiul', 'jalanõuderiiuli', 'jalanõuderiiulit', 'полиця для взуття'),
  Lexeme('n', 'peegel', 'peegli', 'peeglit', 'дзеркало'),
  Lexeme('n', 'vaip', 'vaiba', 'vaipa', 'килим'),
  Lexeme('n', 'kardin', 'kardina', 'kardinat', 'штора'),
  Lexeme('n', 'padi', 'padja', 'patja', 'подушка'),
  Lexeme('n', 'tekk', 'teki', 'tekki', 'ковдра'),
  Lexeme('n', 'kummut', 'kummuti', 'kummutit', 'комод'),
  Lexeme('n', 'lamp', 'lambi', 'lampi', 'лампа'),
  Lexeme('n', 'taskulamp', 'taskulambi', 'taskulampi', 'ліхтарик'),
  Lexeme('n', 'kell', 'kella', 'kella', 'годинник; година'),
  Lexeme('n', 'kalender', 'kalendri', 'kalendrit', 'календар'),
  Lexeme('n', 'plakat', 'plakati', 'plakatit', 'плакат'),
  Lexeme('n', 'maal', 'maali', 'maali', 'картина'),
  Lexeme('n', 'teler', 'teleri', 'telerit', 'телевізор'),
  Lexeme('n', 'televiisor', 'televiisori', 'televiisorit', 'телевізор'),
  Lexeme('n', 'raadio', 'raadio', 'raadiot', 'радіо'),
  Lexeme('n', 'arvuti', 'arvuti', 'arvutit', 'комп’ютер'),
  Lexeme('n', 'sülearvuti', 'sülearvuti', 'sülearvutit', 'ноутбук'),
  Lexeme('n', 'arvutihiir', 'arvutihiire', 'arvutihiirt', 'комп’ютерна мишка'),
  Lexeme('n', 'külmik', 'külmiku', 'külmikut', 'холодильник'),
  Lexeme('n', 'külmkapp', 'külmkapi', 'külmkappi', 'холодильник'),
  Lexeme('n', 'sügavkülmik', 'sügavkülmiku', 'sügavkülmikut', 'морозильник'),
  Lexeme('n', 'pliit', 'pliidi', 'pliiti', 'плита'),
  Lexeme('n', 'ahi', 'ahju', 'ahju', 'піч, духовка'),
  Lexeme('n', 'mikrolaineahi', 'mikrolaineahju', 'mikrolaineahju', 'мікрохвильова піч'),
  Lexeme('n', 'pitsaahi', 'pitsaahju', 'pitsaahju', 'піца-піч'),
  Lexeme('n', 'veekeetja', 'veekeetja', 'veekeetjat', 'електрочайник'),
  Lexeme('n', 'pesumasin', 'pesumasina', 'pesumasinat', 'пральна машина'),
  Lexeme('n', 'nõudepesumasin', 'nõudepesumasina', 'nõudepesumasinat', 'посудомийна машина'),
  Lexeme('n', 'köögikombain', 'köögikombaini', 'köögikombaini', 'кухонний комбайн'),
  Lexeme('n', 'köögitehnika', 'köögitehnika', 'köögitehnikat', 'кухонна техніка'),
  Lexeme('n', 'kraanikauss', 'kraanikausi', 'kraanikaussi', 'умивальник'),
  Lexeme('n', 'dušš', 'duši', 'dušši', 'душ'),
  Lexeme('n', 'dušikabiin', 'dušikabiini', 'dušikabiini', 'душова кабіна'),
  Lexeme('n', 'vann', 'vanni', 'vanni', 'ванна'),
  Lexeme('n', 'mullivann', 'mullivanni', 'mullivanni', 'джакузі'),
  Lexeme('n', 'nagi', 'nagi', 'nagi', 'вішалка'),
  Lexeme('n', 'riidenagi', 'riidenagi', 'riidenagi', 'вішалка для одягу'),
  Lexeme('n', 'kast', 'kasti', 'kasti', 'ящик, коробка'),
  Lexeme('n', 'vihik', 'vihiku', 'vihikut', 'зошит', 'vihikuid'),
  Lexeme('n', 'raamat', 'raamatu', 'raamatut', 'книга', 'raamatuid'),
  Lexeme('n', 'koolikott', 'koolikoti', 'koolikotti', 'шкільний рюкзак'),
  Lexeme('n', 'kott', 'koti', 'kotti', 'сумка'),
  Lexeme('n', 'king', 'kinga', 'kinga', 'туфля', 'kingi'),
  Lexeme('n', 'jalanõu', 'jalanõu', 'jalanõu', 'взуття'),
  Lexeme('n', 'suss', 'sussi', 'sussi', 'капець'),
  Lexeme('n', 'jope', 'jope', 'jopet', 'куртка'),
  Lexeme('n', 'riie', 'riide', 'riiet', 'одяг, тканина'),
  Lexeme('n', 'kosmeetika', 'kosmeetika', 'kosmeetikat', 'косметика'),
  Lexeme('n', 'akvaarium', 'akvaariumi', 'akvaariumi', 'акваріум'),
  Lexeme('n', 'saun', 'sauna', 'sauna', 'сауна'),
  Lexeme('n', 'wifi', 'wifi', 'wifit', 'вайфай'),
  Lexeme('n', 'mööbel', 'mööbli', 'mööblit', 'меблі'),
  Lexeme('n', 'asi', 'asja', 'asja', 'річ', 'asju'),
  Lexeme('n', 'pass', 'passi', 'passi', 'паспорт'),
  // ---------------- Гараж и инструменты ----------------
  Lexeme('n', 'haamer', 'haamri', 'haamrit', 'молоток'),
  Lexeme('n', 'tööriist', 'tööriista', 'tööriista', 'інструмент'),
  Lexeme('n', 'jalgratas', 'jalgratta', 'jalgratast', 'велосипед'),
  Lexeme('n', 'ratas', 'ratta', 'ratast', 'колесо; велосипед'),
  Lexeme('n', 'redel', 'redeli', 'redelit', 'драбина'),
  Lexeme('n', 'kanister', 'kanistri', 'kanistrit', 'каністра'),
  Lexeme('n', 'kaabel', 'kaabli', 'kaablit', 'кабель'),
  Lexeme('n', 'muruniiduk', 'muruniiduki', 'muruniidukit', 'газонокосарка'),
  Lexeme('n', 'rehv', 'rehvi', 'rehvi', 'шина'),
  Lexeme('n', 'suverehv', 'suverehvi', 'suverehvi', 'літня шина'),
  Lexeme('n', 'nöör', 'nööri', 'nööri', 'мотузка'),
  Lexeme('n', 'auto', 'auto', 'autot', 'автомобіль'),
  // ---------------- Люди и животные ----------------
  Lexeme('n', 'pere', 'pere', 'peret', 'сім’я'),
  Lexeme('n', 'perekond', 'perekonna', 'perekonda', 'родина'),
  Lexeme('n', 'ema', 'ema', 'ema', 'мама'),
  Lexeme('n', 'isa', 'isa', 'isa', 'тато'),
  Lexeme('n', 'vend', 'venna', 'venda', 'брат'),
  Lexeme('n', 'õde', 'õe', 'õde', 'сестра'),
  Lexeme('n', 'poeg', 'poja', 'poega', 'син'),
  Lexeme('n', 'laps', 'lapse', 'last', 'дитина'),
  Lexeme('n', 'vanaema', 'vanaema', 'vanaema', 'бабуся'),
  Lexeme('n', 'onu', 'onu', 'onu', 'дядько'),
  Lexeme('n', 'tädi', 'tädi', 'tädi', 'тітка'),
  Lexeme('n', 'naine', 'naise', 'naist', 'жінка, дружина'),
  Lexeme('n', 'mees', 'mehe', 'meest', 'чоловік'),
  Lexeme('n', 'sõber', 'sõbra', 'sõpra', 'друг', 'sõpru'),
  Lexeme('n', 'sõbranna', 'sõbranna', 'sõbrannat', 'подруга'),
  Lexeme('n', 'naaber', 'naabri', 'naabrit', 'сусід'),
  Lexeme('n', 'naabermaja', 'naabermaja', 'naabermaja', 'сусідній будинок'),
  Lexeme('n', 'inimene', 'inimese', 'inimest', 'людина'),
  Lexeme('n', 'elanik', 'elaniku', 'elanikku', 'мешканець', 'elanikke'),
  Lexeme('n', 'kunstnik', 'kunstniku', 'kunstnikku', 'художник'),
  Lexeme('n', 'õpilane', 'õpilase', 'õpilast', 'учень'),
  Lexeme('n', 'üliõpilane', 'üliõpilase', 'üliõpilast', 'студент'),
  Lexeme('n', 'õpetaja', 'õpetaja', 'õpetajat', 'вчитель'),
  Lexeme('n', 'pensionär', 'pensionäri', 'pensionäri', 'пенсіонер'),
  Lexeme('n', 'treener', 'treeneri', 'treenerit', 'тренер'),
  Lexeme('n', 'ujumistreener', 'ujumistreeneri', 'ujumistreenerit', 'тренер з плавання'),
  Lexeme('n', 'spetsialist', 'spetsialisti', 'spetsialisti', 'спеціаліст'),
  Lexeme('n', 'klient', 'kliendi', 'klienti', 'клієнт', 'kliente'),
  Lexeme('n', 'kass', 'kassi', 'kassi', 'кіт'),
  Lexeme('n', 'koer', 'koera', 'koera', 'собака'),
  Lexeme('n', 'hamster', 'hamstri', 'hamstrit', 'хом’як'),
  Lexeme('n', 'papagoi', 'papagoi', 'papagoid', 'папуга'),
  Lexeme('n', 'lind', 'linnu', 'lindu', 'птах', 'linde'),
  Lexeme('n', 'kutsikas', 'kutsika', 'kutsikat', 'цуценя'),
  Lexeme('n', 'puur', 'puuri', 'puuri', 'клітка'),
  Lexeme('n', 'loom', 'looma', 'looma', 'тварина'),
  // ---------------- Медицина ----------------
  Lexeme('n', 'arst', 'arsti', 'arsti', 'лікар'),
  Lexeme('n', 'perearst', 'perearsti', 'perearsti', 'сімейний лікар'),
  Lexeme('n', 'lastearst', 'lastearsti', 'lastearsti', 'педіатр'),
  Lexeme('n', 'nahaarst', 'nahaarsti', 'nahaarsti', 'дерматолог'),
  Lexeme('n', 'silmaarst', 'silmaarsti', 'silmaarsti', 'окуліст'),
  Lexeme('n', 'hambaarst', 'hambaarsti', 'hambaarsti', 'стоматолог'),
  Lexeme('n', 'patsient', 'patsiendi', 'patsienti', 'пацієнт'),
  Lexeme('n', 'psühholoog', 'psühholoogi', 'psühholoogi', 'психолог'),
  Lexeme('n', 'füsioterapeut', 'füsioterapeudi', 'füsioterapeuti', 'фізіотерапевт'),
  Lexeme('n', 'polikliinik', 'polikliiniku', 'polikliinikut', 'поліклініка'),
  Lexeme('n', 'registratuur', 'registratuuri', 'registratuuri', 'реєстратура'),
  Lexeme('n', 'hoone', 'hoone', 'hoonet', 'будівля'),
  Lexeme('n', 'röntgen', 'röntgeni', 'röntgenit', 'рентген'),
  Lexeme('n', 'ultraheli', 'ultraheli', 'ultraheli', 'УЗД'),
  Lexeme('n', 'uuring', 'uuringu', 'uuringut', 'обстеження'),
  Lexeme('n', 'nõustamine', 'nõustamise', 'nõustamist', 'консультація'),
  Lexeme('n', 'abi', 'abi', 'abi', 'допомога'),
  Lexeme('n', 'vastuvõtt', 'vastuvõtu', 'vastuvõttu', 'прийом'),
  Lexeme('n', 'järjekorranumber', 'järjekorranumbri', 'järjekorranumbrit', 'номер черги'),
  // ---------------- Город и природа ----------------
  Lexeme('n', 'linn', 'linna', 'linna', 'місто'),
  Lexeme('n', 'kodulinn', 'kodulinna', 'kodulinna', 'рідне місто'),
  Lexeme('n', 'kesklinn', 'kesklinna', 'kesklinna', 'центр міста'),
  Lexeme('n', 'äärelinn', 'äärelinna', 'äärelinna', 'передмістя'),
  Lexeme('n', 'linnaosa', 'linnaosa', 'linnaosa', 'район міста'),
  Lexeme('n', 'tänav', 'tänava', 'tänavat', 'вулиця'),
  Lexeme('n', 'park', 'pargi', 'parki', 'парк'),
  Lexeme('n', 'parkla', 'parkla', 'parklat', 'парковка'),
  Lexeme('n', 'pood', 'poe', 'poodi', 'магазин'),
  Lexeme('n', 'toidupood', 'toidupoe', 'toidupoodi', 'продуктовий магазин'),
  Lexeme('n', 'apteek', 'apteegi', 'apteeki', 'аптека'),
  Lexeme('n', 'kool', 'kooli', 'kooli', 'школа'),
  Lexeme('n', 'klass', 'klassi', 'klassi', 'клас'),
  Lexeme('n', 'lasteaed', 'lasteaia', 'lasteaeda', 'дитячий садок'),
  Lexeme('n', 'kohvik', 'kohviku', 'kohvikut', 'кафе'),
  Lexeme('n', 'turg', 'turu', 'turgu', 'ринок'),
  Lexeme('n', 'kiosk', 'kioski', 'kioskit', 'кіоск'),
  Lexeme('n', 'spordiväljak', 'spordiväljaku', 'spordiväljakut', 'спортмайданчик'),
  Lexeme('n', 'mänguväljak', 'mänguväljaku', 'mänguväljakut', 'ігровий майданчик'),
  Lexeme('n', 'staadion', 'staadioni', 'staadioni', 'стадіон'),
  Lexeme('n', 'hotell', 'hotelli', 'hotelli', 'готель'),
  Lexeme('n', 'restoran', 'restorani', 'restorani', 'ресторан'),
  Lexeme('n', 'salong', 'salongi', 'salongi', 'салон'),
  Lexeme('n', 'firma', 'firma', 'firmat', 'фірма'),
  Lexeme('n', 'bassein', 'basseini', 'basseini', 'басейн'),
  Lexeme('n', 'ujula', 'ujula', 'ujulat', 'басейн (заклад)'),
  Lexeme('n', 'bussipeatus', 'bussipeatuse', 'bussipeatust', 'автобусна зупинка'),
  Lexeme('n', 'meri', 'mere', 'merd', 'море'),
  Lexeme('n', 'järv', 'järve', 'järve', 'озеро'),
  Lexeme('n', 'mägi', 'mäe', 'mäge', 'гора'),
  Lexeme('n', 'mets', 'metsa', 'metsa', 'ліс'),
  Lexeme('n', 'jõgi', 'jõe', 'jõge', 'річка'),
  Lexeme('n', 'rand', 'ranna', 'randa', 'пляж, берег'),
  Lexeme('n', 'loodus', 'looduse', 'loodust', 'природа'),
  Lexeme('n', 'lill', 'lille', 'lille', 'квітка', 'lilli'),
  Lexeme('n', 'taim', 'taime', 'taime', 'рослина'),
  Lexeme('n', 'maitsetaim', 'maitsetaime', 'maitsetaime', 'пряна трава'),
  Lexeme('n', 'viljapuu', 'viljapuu', 'viljapuud', 'фруктове дерево'),
  Lexeme('n', 'puu', 'puu', 'puud', 'дерево'),
  Lexeme('n', 'mari', 'marja', 'marja', 'ягода'),
  Lexeme('n', 'rohelus', 'roheluse', 'rohelust', 'зелень'),
  Lexeme('n', 'linnulaul', 'linnulaulu', 'linnulaulu', 'спів птахів'),
  Lexeme('n', 'ilm', 'ilma', 'ilma', 'погода'),
  Lexeme('n', 'päike', 'päikese', 'päikest', 'сонце'),
  Lexeme('n', 'valgus', 'valguse', 'valgust', 'світло'),
  Lexeme('n', 'õu', 'õue', 'õue', 'двір'),
  Lexeme('n', 'turismitalu', 'turismitalu', 'turismitalu', 'туристична садиба'),
  Lexeme('n', 'kanuumatk', 'kanuumatka', 'kanuumatka', 'каное-похід'),
  Lexeme('n', 'külaskäik', 'külaskäigu', 'külaskäiku', 'візит'),
  Lexeme('n', 'ööbimine', 'ööbimise', 'ööbimist', 'ночівля'),
  // ---------------- Еда и напитки ----------------
  Lexeme('n', 'supp', 'supi', 'suppi', 'суп'),
  Lexeme('n', 'kohv', 'kohvi', 'kohvi', 'кава'),
  Lexeme('n', 'tee', 'tee', 'teed', 'чай; дорога'),
  Lexeme('n', 'vesi', 'vee', 'vett', 'вода'),
  Lexeme('n', 'piim', 'piima', 'piima', 'молоко'),
  Lexeme('n', 'puder', 'pudru', 'putru', 'каша'),
  Lexeme('n', 'muna', 'muna', 'muna', 'яйце'),
  Lexeme('n', 'salat', 'salati', 'salatit', 'салат'),
  Lexeme('n', 'toit', 'toidu', 'toitu', 'їжа'),
  Lexeme('n', 'hommikusöök', 'hommikusöögi', 'hommikusööki', 'сніданок'),
  Lexeme('n', 'makaron', 'makaroni', 'makaroni', 'макарони', 'makarone'),
  Lexeme('n', 'riis', 'riisi', 'riisi', 'рис'),
  Lexeme('n', 'konserv', 'konservi', 'konservi', 'консерва', 'konserve'),
  Lexeme('n', 'puuvili', 'puuvilja', 'puuvilja', 'фрукт'),
  Lexeme('n', 'tomat', 'tomati', 'tomatit', 'помідор', 'tomateid'),
  Lexeme('n', 'mesi', 'mee', 'mett', 'мед'),
  Lexeme('n', 'maiustus', 'maiustuse', 'maiustust', 'ласощі', 'maiustusi'),
  Lexeme('n', 'retsept', 'retsepti', 'retsepti', 'рецепт', 'retsepte'),
  Lexeme('n', 'klaas', 'klaasi', 'klaasi', 'склянка'),
  // ---------------- Абстрактное, время, разное ----------------
  Lexeme('n', 'nimi', 'nime', 'nime', 'ім’я'),
  Lexeme('n', 'perekonnanimi', 'perekonnanime', 'perekonnanime', 'прізвище'),
  Lexeme('n', 'number', 'numbri', 'numbrit', 'номер, число'),
  Lexeme('n', 'keel', 'keele', 'keelt', 'мова; язик'),
  Lexeme('n', 'sõna', 'sõna', 'sõna', 'слово'),
  Lexeme('n', 'ruutmeeter', 'ruutmeetri', 'ruutmeetrit', 'квадратний метр'),
  Lexeme('n', 'meeter', 'meetri', 'meetrit', 'метр'),
  Lexeme('n', 'hind', 'hinna', 'hinda', 'ціна'),
  Lexeme('n', 'raha', 'raha', 'raha', 'гроші'),
  Lexeme('n', 'euro', 'euro', 'eurot', 'євро'),
  Lexeme('n', 'rahatäht', 'rahatähe', 'rahatähte', 'банкнота'),
  Lexeme('n', 'üür', 'üüri', 'üüri', 'оренда'),
  Lexeme('n', 'kommunaalid', 'kommunaalide', 'kommunaale', 'комунальні платежі'),
  Lexeme('n', 'kuulutus', 'kuulutuse', 'kuulutust', 'оголошення'),
  Lexeme('n', 'maakler', 'maakleri', 'maaklerit', 'ріелтор'),
  Lexeme('n', 'fonolukk', 'fonoluki', 'fonolukku', 'домофон'),
  Lexeme('n', 'videovalve', 'videovalve', 'videovalvet', 'відеонагляд'),
  Lexeme('n', 'töö', 'töö', 'tööd', 'робота'),
  Lexeme('n', 'tööpäev', 'tööpäeva', 'tööpäeva', 'робочий день'),
  Lexeme('n', 'hobi', 'hobi', 'hobi', 'хобі'),
  Lexeme('n', 'film', 'filmi', 'filmi', 'фільм', 'filme'),
  Lexeme('n', 'muusika', 'muusika', 'muusikat', 'музика'),
  Lexeme('n', 'pill', 'pilli', 'pilli', 'музичний інструмент'),
  Lexeme('n', 'kitarr', 'kitarri', 'kitarri', 'гітара'),
  Lexeme('n', 'klaver', 'klaveri', 'klaverit', 'піаніно'),
  Lexeme('n', 'male', 'male', 'malet', 'шахи'),
  Lexeme('n', 'kaart', 'kaardi', 'kaarti', 'карта', 'kaarte'),
  Lexeme('n', 'uudis', 'uudise', 'uudist', 'новина', 'uudiseid'),
  Lexeme('n', 'lugemine', 'lugemise', 'lugemist', 'читання'),
  Lexeme('n', 'kudumine', 'kudumise', 'kudumist', 'в’язання'),
  Lexeme('n', 'jooksmine', 'jooksmise', 'jooksmist', 'біг'),
  Lexeme('n', 'fotograafia', 'fotograafia', 'fotograafiat', 'фотографія'),
  Lexeme('n', 'matkamine', 'matkamise', 'matkamist', 'похід'),
  Lexeme('n', 'reisimine', 'reisimise', 'reisimist', 'подорожі'),
  Lexeme('n', 'iseloom', 'iseloomu', 'iseloomu', 'характер'),
  Lexeme('n', 'päästja', 'päästja', 'päästjat', 'рятувальник'),
  Lexeme('n', 'päästekomando', 'päästekomando', 'päästekomandot', 'рятувальна команда'),
  Lexeme('n', 'raamatukogu', 'raamatukogu', 'raamatukogu', 'бібліотека'),
  Lexeme('n', 'raamatukoguhoidja', 'raamatukoguhoidja', 'raamatukoguhoidjat', 'бібліотекар'),
  Lexeme('n', 'kokk', 'koka', 'kokka', 'кухар'),
  Lexeme('n', 'küünetehnik', 'küünetehniku', 'küünetehnikut', 'майстер манікюру'),
  Lexeme('n', 'taksojuht', 'taksojuhi', 'taksojuhti', 'таксист'),
  Lexeme('n', 'programmeerija', 'programmeerija', 'programmeerijat', 'програміст'),
  Lexeme('n', 'käsi', 'käe', 'kätt', 'рука'),
  Lexeme('n', 'nägu', 'näo', 'nägu', 'обличчя'),
  Lexeme('n', 'hommik', 'hommiku', 'hommikut', 'ранок'),
  Lexeme('n', 'õhtu', 'õhtu', 'õhtut', 'вечір'),
  Lexeme('n', 'päev', 'päeva', 'päeva', 'день'),
  Lexeme('n', 'öö', 'öö', 'ööd', 'ніч'),
  Lexeme('n', 'nädal', 'nädala', 'nädalat', 'тиждень'),
  Lexeme('n', 'nädalavahetus', 'nädalavahetuse', 'nädalavahetust', 'вихідні'),
  Lexeme('n', 'aasta', 'aasta', 'aastat', 'рік', 'aastaid'),
  Lexeme('n', 'aeg', 'aja', 'aega', 'час'),
  Lexeme('n', 'kuupäev', 'kuupäeva', 'kuupäeva', 'дата'),
  Lexeme('n', 'koht', 'koha', 'kohta', 'місце'),
  Lexeme('n', 'ruum', 'ruumi', 'ruumi', 'приміщення, простір', 'ruume'),
  Lexeme('n', 'kääne', 'käände', 'käänet', 'відмінок'),
  Lexeme('n', 'vorm', 'vormi', 'vormi', 'форма'),
  Lexeme('n', 'eitus', 'eituse', 'eitust', 'заперечення'),
  Lexeme('n', 'puudumine', 'puudumise', 'puudumist', 'відсутність'),
  Lexeme('n', 'lehekülg', 'lehekülje', 'lehekülge', 'сторінка'),
  Lexeme('n', 'arve', 'arve', 'arvet', 'рахунок'),
  Lexeme('n', 'kaktus', 'kaktuse', 'kaktust', 'кактус'),
  Lexeme('n', 'sünnipäev', 'sünnipäeva', 'sünnipäeva', 'день народження'),
  Lexeme('n', 'tennis', 'tennise', 'tennist', 'теніс'),
  Lexeme('n', 'korvpall', 'korvpalli', 'korvpalli', 'баскетбол'),
  Lexeme('n', 'jalgpall', 'jalgpalli', 'jalgpalli', 'футбол'),
  Lexeme('n', 'porgand', 'porgandi', 'porgandit', 'морква'),
  Lexeme('n', 'seeme', 'seemne', 'seemet', 'насінина', 'seemneid'),
  Lexeme('n', 'õun', 'õuna', 'õuna', 'яблуко'),
  Lexeme('n', 'mänguasi', 'mänguasja', 'mänguasja', 'іграшка'),
  Lexeme('n', 'värav', 'värava', 'väravat', 'ворота'),
  Lexeme('n', 'grivna', 'grivna', 'grivnat', 'гривня'),
  Lexeme('n', 'summa', 'summa', 'summat', 'сума'),
  Lexeme('n', 'pits', 'pitsa', 'pitsat', 'піца'),
  Lexeme('n', 'jäätis', 'jäätise', 'jäätist', 'морозиво'),
  Lexeme('n', 'rahamõistatus', 'rahamõistatuse', 'rahamõistatust', 'грошова загадка'),
  Lexeme('n', 'matemaatika', 'matemaatika', 'matemaatikat', 'математика'),
  Lexeme('n', 'füüsika', 'füüsika', 'füüsikat', 'фізика'),
  Lexeme('n', 'ajalugu', 'ajaloo', 'ajalugu', 'історія'),
  Lexeme('n', 'ajaleht', 'ajalehe', 'ajalehte', 'газета'),
  Lexeme('n', 'hambapasta', 'hambapasta', 'hambapastat', 'зубна паста'),
  Lexeme('n', 'hambahari', 'hambaharja', 'hambaharja', 'зубна щітка'),
  Lexeme('n', 'minut', 'minuti', 'minutit', 'хвилина'),
  Lexeme('n', 'stuudiokorter', 'stuudiokorteri', 'stuudiokorterit', 'квартира-студія'),
  Lexeme('n', 'eramaja', 'eramaja', 'eramaja', 'приватний будинок'),
  Lexeme('n', 'tellismaja', 'tellismaja', 'tellismaja', 'цегляний будинок'),
  Lexeme('n', 'paneelmaja', 'paneelmaja', 'paneelmaja', 'панельний будинок'),
  // ---------------- Числительные и порядковые ----------------
  Lexeme('a', 'üks', 'ühe', 'üht', 'один'),
  Lexeme('a', 'kaks', 'kahe', 'kaht', 'два'),
  Lexeme('a', 'kolm', 'kolme', 'kolme', 'три'),
  Lexeme('a', 'neli', 'nelja', 'nelja', 'чотири'),
  Lexeme('a', 'viis', 'viie', 'viit', 'п’ять'),
  Lexeme('a', 'kuus', 'kuue', 'kuut', 'шість'),
  Lexeme('a', 'seitse', 'seitsme', 'seitset', 'сім'),
  Lexeme('a', 'kaheksa', 'kaheksa', 'kaheksat', 'вісім'),
  Lexeme('a', 'üheksa', 'üheksa', 'üheksat', 'дев’ять'),
  Lexeme('a', 'kümme', 'kümne', 'kümmet', 'десять'),
  Lexeme('a', 'sada', 'saja', 'sadat', 'сто'),
  Lexeme('a', 'esimene', 'esimese', 'esimest', 'перший'),
  Lexeme('a', 'teine', 'teise', 'teist', 'другий'),
  Lexeme('a', 'kolmas', 'kolmanda', 'kolmandat', 'третій'),
  Lexeme('a', 'neljas', 'neljanda', 'neljandat', 'четвертий'),
  Lexeme('a', 'viies', 'viienda', 'viiendat', 'п’ятий'),
  Lexeme('a', 'kuues', 'kuuenda', 'kuuendat', 'шостий'),
  Lexeme('a', 'seitsmes', 'seitsmenda', 'seitsmendat', 'сьомий'),
  Lexeme('a', 'kaheksas', 'kaheksanda', 'kaheksandat', 'восьмий'),
  Lexeme('a', 'üheksas', 'üheksanda', 'üheksandat', 'дев’ятий'),
  Lexeme('a', 'kümnes', 'kümnenda', 'kümnendat', 'десятий'),
  Lexeme('a', 'üheteistkümnes', 'üheteistkümnenda', 'üheteistkümnendat', 'одинадцятий'),
  Lexeme('a', 'mõlemad', 'mõlema', 'mõlemat', 'обидва'),
  // ---------------- Прилагательные ----------------
  Lexeme('a', 'suur', 'suure', 'suurt', 'великий'),
  Lexeme('a', 'väike', 'väikese', 'väikest', 'маленький'),
  Lexeme('a', 'uus', 'uue', 'uut', 'новий', 'uusi'),
  Lexeme('a', 'vana', 'vana', 'vana', 'старий', 'vanu'),
  Lexeme('a', 'hea', 'hea', 'head', 'хороший'),
  Lexeme('a', 'ilus', 'ilusa', 'ilusat', 'гарний'),
  Lexeme('a', 'soe', 'sooja', 'sooja', 'теплий'),
  Lexeme('a', 'külm', 'külma', 'külma', 'холодний'),
  Lexeme('a', 'kuum', 'kuuma', 'kuuma', 'гарячий'),
  Lexeme('a', 'hele', 'heleda', 'heledat', 'світлий'),
  Lexeme('a', 'tumehall', 'tumehalli', 'tumehalli', 'темно-сірий'),
  Lexeme('a', 'valge', 'valge', 'valget', 'білий'),
  Lexeme('a', 'must', 'musta', 'musta', 'чорний'),
  Lexeme('a', 'punane', 'punase', 'punast', 'червоний'),
  Lexeme('a', 'roheline', 'rohelise', 'rohelist', 'зелений'),
  Lexeme('a', 'kollane', 'kollase', 'kollast', 'жовтий'),
  Lexeme('a', 'sinine', 'sinise', 'sinist', 'синій'),
  Lexeme('a', 'pruun', 'pruuni', 'pruuni', 'коричневий'),
  Lexeme('a', 'hall', 'halli', 'halli', 'сірий'),
  Lexeme('a', 'kreemikas', 'kreemika', 'kreemikat', 'кремовий'),
  Lexeme('a', 'pehme', 'pehme', 'pehmet', 'м’який'),
  Lexeme('a', 'puhas', 'puhta', 'puhast', 'чистий'),
  Lexeme('a', 'mugav', 'mugava', 'mugavat', 'зручний'),
  Lexeme('a', 'hubane', 'hubase', 'hubast', 'затишний'),
  Lexeme('a', 'avar', 'avara', 'avarat', 'просторий'),
  Lexeme('a', 'valgusküllane', 'valgusküllase', 'valgusküllast', 'світлий, повний світла'),
  Lexeme('a', 'vaikne', 'vaikse', 'vaikset', 'тихий'),
  Lexeme('a', 'jahe', 'jaheda', 'jahedat', 'прохолодний'),
  Lexeme('a', 'kitsas', 'kitsa', 'kitsast', 'вузький'),
  Lexeme('a', 'lai', 'laia', 'laia', 'широкий'),
  Lexeme('a', 'pikk', 'pika', 'pikka', 'довгий'),
  Lexeme('a', 'õhuke', 'õhukese', 'õhukest', 'тонкий'),
  Lexeme('a', 'rahulik', 'rahuliku', 'rahulikku', 'спокійний'),
  Lexeme('a', 'sõbralik', 'sõbraliku', 'sõbralikku', 'дружелюбний'),
  Lexeme('a', 'viisakas', 'viisaka', 'viisakat', 'ввічливий'),
  Lexeme('a', 'abivalmis', 'abivalmis', 'abivalmis', 'готовий допомогти'),
  Lexeme('a', 'rõõmsameelne', 'rõõmsameelse', 'rõõmsameelset', 'веселий'),
  Lexeme('a', 'töökas', 'tööka', 'töökat', 'працьовитий'),
  Lexeme('a', 'noor', 'noore', 'noort', 'молодий'),
  Lexeme('a', 'tore', 'toreda', 'toredat', 'чудовий'),
  Lexeme('a', 'huvitav', 'huvitava', 'huvitavat', 'цікавий'),
  Lexeme('a', 'vaba', 'vaba', 'vaba', 'вільний', 'vabu'),
  Lexeme('a', 'kaasaegne', 'kaasaegse', 'kaasaegset', 'сучасний'),
  Lexeme('a', 'ideaalne', 'ideaalse', 'ideaalset', 'ідеальний'),
  Lexeme('a', 'lihtne', 'lihtsa', 'lihtsat', 'простий'),
  Lexeme('a', 'raske', 'raske', 'rasket', 'важкий'),
  Lexeme('a', 'kiire', 'kiire', 'kiiret', 'швидкий'),
  Lexeme('a', 'odav', 'odava', 'odavat', 'дешевий'),
  Lexeme('a', 'värske', 'värske', 'värsket', 'свіжий'),
  Lexeme('a', 'täpne', 'täpse', 'täpset', 'точний'),
  Lexeme('a', 'kindel', 'kindla', 'kindlat', 'певний, надійний'),
  Lexeme('a', 'erinev', 'erineva', 'erinevat', 'різний'),
  Lexeme('a', 'üheaastane', 'üheaastase', 'üheaastast', 'однорічний'),
  Lexeme('a', 'kahekohaline', 'kahekohalise', 'kahekohalist', 'двомісний'),
  Lexeme('a', 'kolmetoaline', 'kolmetoalise', 'kolmetoalist', 'трикімнатний'),
  Lexeme('a', 'ühetoaline', 'ühetoalise', 'ühetoalist', 'однокімнатний'),
  Lexeme('a', 'kahetoaline', 'kahetoalise', 'kahetoalist', 'двокімнатний'),
  Lexeme('a', 'neljakuune', 'neljakuuse', 'neljakuust', 'чотиримісячний'),
  Lexeme('a', 'viiekorruseline', 'viiekorruselise', 'viiekorruselist', 'п’ятиповерховий'),
  Lexeme('a', 'kuuekorruseline', 'kuuekorruselise', 'kuuekorruselist', 'шестиповерховий'),
  Lexeme('a', 'kuuekohaline', 'kuuekohalise', 'kuuekohalist', 'шестимісний'),
  Lexeme('a', 'kaheksatunnine', 'kaheksatunnise', 'kaheksatunnist', 'восьмигодинний'),
  Lexeme('a', 'kümneeurone', 'kümneeurose', 'kümneeurost', 'десятиєвровий'),
  // ---------------- Глаголы ----------------
  Lexeme('v', 'olema', 'olla', 'ole', 'бути'),
  Lexeme('v', 'elama', 'elada', 'ela', 'жити'),
  Lexeme('v', 'töötama', 'töötada', 'tööta', 'працювати'),
  Lexeme('v', 'õppima', 'õppida', 'õpi', 'вчитися'),
  Lexeme('v', 'õpetama', 'õpetada', 'õpeta', 'викладати'),
  Lexeme('v', 'minema', 'minna', 'lähe', 'йти'),
  Lexeme('v', 'tulema', 'tulla', 'tule', 'приходити'),
  Lexeme('v', 'sõitma', 'sõita', 'sõida', 'їхати'),
  Lexeme('v', 'käima', 'käia', 'käi', 'ходити'),
  Lexeme('v', 'vaatama', 'vaadata', 'vaata', 'дивитися'),
  Lexeme('v', 'nägema', 'näha', 'näe', 'бачити'),
  Lexeme('v', 'lugema', 'lugeda', 'loe', 'читати'),
  Lexeme('v', 'kirjutama', 'kirjutada', 'kirjuta', 'писати'),
  Lexeme('v', 'mängima', 'mängida', 'mängi', 'грати'),
  Lexeme('v', 'sööma', 'süüa', 'söö', 'їсти'),
  Lexeme('v', 'jooma', 'juua', 'joo', 'пити'),
  Lexeme('v', 'tegema', 'teha', 'tee', 'робити'),
  Lexeme('v', 'valmistama', 'valmistada', 'valmista', 'готувати'),
  Lexeme('v', 'pesema', 'pesta', 'pese', 'мити'),
  Lexeme('v', 'ärkama', 'ärgata', 'ärka', 'прокидатися'),
  Lexeme('v', 'magama', 'magada', 'maga', 'спати'),
  Lexeme('v', 'puhkama', 'puhata', 'puhka', 'відпочивати'),
  Lexeme('v', 'istuma', 'istuda', 'istu', 'сидіти'),
  Lexeme('v', 'seisma', 'seista', 'seisa', 'стояти'),
  Lexeme('v', 'rippuma', 'rippuda', 'ripu', 'висіти'),
  Lexeme('v', 'jooksma', 'joosta', 'jookse', 'бігати'),
  Lexeme('v', 'jalutama', 'jalutada', 'jaluta', 'гуляти'),
  Lexeme('v', 'ujuma', 'ujuda', 'uju', 'плавати'),
  Lexeme('v', 'tahtma', 'tahta', 'taha', 'хотіти'),
  Lexeme('v', 'soovima', 'soovida', 'soovi', 'бажати'),
  Lexeme('v', 'armastama', 'armastada', 'armasta', 'любити'),
  Lexeme('v', 'meeldima', 'meeldida', 'meeldi', 'подобатися'),
  Lexeme('v', 'oskama', 'osata', 'oska', 'вміти'),
  Lexeme('v', 'saama', 'saada', 'saa', 'отримувати; могти'),
  Lexeme('v', 'võtma', 'võtta', 'võta', 'брати'),
  Lexeme('v', 'panema', 'panna', 'pane', 'класти'),
  Lexeme('v', 'hoidma', 'hoida', 'hoia', 'зберігати, тримати'),
  Lexeme('v', 'ostma', 'osta', 'osta', 'купувати'),
  Lexeme('v', 'maksma', 'maksta', 'maksa', 'платити; коштувати'),
  Lexeme('v', 'broneerima', 'broneerida', 'broneeri', 'бронювати'),
  Lexeme('v', 'registreerima', 'registreerida', 'registreeri', 'реєструвати'),
  Lexeme('v', 'helistama', 'helistada', 'helista', 'телефонувати'),
  Lexeme('v', 'rääkima', 'rääkida', 'räägi', 'говорити'),
  Lexeme('v', 'ütlema', 'öelda', 'ütle', 'казати'),
  Lexeme('v', 'küsima', 'küsida', 'küsi', 'питати'),
  Lexeme('v', 'vastama', 'vastata', 'vasta', 'відповідати'),
  Lexeme('v', 'kuulama', 'kuulata', 'kuula', 'слухати'),
  Lexeme('v', 'kuulma', 'kuulda', 'kuule', 'чути'),
  Lexeme('v', 'jutustama', 'jutustada', 'jutusta', 'розповідати'),
  Lexeme('v', 'mõtlema', 'mõelda', 'mõtle', 'думати'),
  Lexeme('v', 'teadma', 'teada', 'tea', 'знати'),
  Lexeme('v', 'leidma', 'leida', 'leia', 'знаходити'),
  Lexeme('v', 'asuma', 'asuda', 'asu', 'розташовуватися'),
  Lexeme('v', 'kolima', 'kolida', 'koli', 'переїжджати'),
  Lexeme('v', 'kasvama', 'kasvada', 'kasva', 'рости'),
  Lexeme('v', 'kasvatama', 'kasvatada', 'kasvata', 'вирощувати'),
  Lexeme('v', 'algama', 'alata', 'alga', 'починатися'),
  Lexeme('v', 'aitama', 'aidata', 'aita', 'допомагати'),
  Lexeme('v', 'lõikama', 'lõigata', 'lõika', 'різати'),
  Lexeme('v', 'riputama', 'riputada', 'riputa', 'вішати'),
  Lexeme('v', 'koristama', 'koristada', 'korista', 'прибирати'),
  Lexeme('v', 'tervitama', 'tervitada', 'tervita', 'вітати'),
  Lexeme('v', 'naeratama', 'naeratada', 'naerata', 'усміхатися'),
  Lexeme('v', 'ootama', 'oodata', 'oota', 'чекати'),
  Lexeme('v', 'viima', 'viia', 'vii', 'відносити, вести'),
  Lexeme('v', 'tooma', 'tuua', 'too', 'приносити'),
  Lexeme('v', 'jõudma', 'jõuda', 'jõua', 'встигати, досягати'),
  Lexeme('v', 'tundma', 'tunda', 'tunne', 'відчувати'),
  Lexeme('v', 'vajama', 'vajata', 'vaja', 'потребувати'),
  Lexeme('v', 'proovima', 'proovida', 'proovi', 'пробувати'),
  Lexeme('v', 'puhastama', 'puhastada', 'puhasta', 'чистити'),
  Lexeme('v', 'avanema', 'avaneda', 'avane', 'відчинятися'),
  Lexeme('v', 'näitama', 'näidata', 'näita', 'показувати'),
  Lexeme('v', 'paistma', 'paista', 'paista', 'світити, виднітися'),
  Lexeme('v', 'hakkama', 'hakata', 'hakka', 'починати'),
  Lexeme('v', 'pidama', 'pidada', 'pea', 'мусити'),
  Lexeme('v', 'maalima', 'maalida', 'maali', 'малювати'),
  Lexeme('v', 'sobima', 'sobida', 'sobi', 'підходити'),
  Lexeme('v', 'mahtuma', 'mahtuda', 'mahu', 'вміщатися'),
  Lexeme('v', 'andma', 'anda', 'anna', 'давати'),
  Lexeme('v', 'igatsema', 'igatseda', 'igatse', 'сумувати за'),
  Lexeme('v', 'tähistama', 'tähistada', 'tähista', 'святкувати'),
  Lexeme('v', 'muutuma', 'muutuda', 'muutu', 'ставати, змінюватися'),
  // ---------------- Послелоги места ----------------
  Lexeme('p', 'juures', '', '', 'біля, при'),
  Lexeme('p', 'juurde', '', '', 'до (кого/чого)'),
  Lexeme('p', 'taga', '', '', 'за, позаду'),
  Lexeme('p', 'ees', '', '', 'перед'),
  Lexeme('p', 'kõrval', '', '', 'поруч'),
  Lexeme('p', 'vastas', '', '', 'навпроти'),
  Lexeme('p', 'kohal', '', '', 'над'),
  Lexeme('p', 'vahel', '', '', 'між; іноді'),
  Lexeme('p', 'all', '', '', 'під'),
  Lexeme('p', 'peal', '', '', 'на (поверхні)'),
  Lexeme('p', 'peale', '', '', 'на (куди)'),
  Lexeme('p', 'ääres', '', '', 'біля, на краю'),
  Lexeme('p', 'äärel', '', '', 'на краю'),
  Lexeme('p', 'lähedal', '', '', 'недалеко'),
  Lexeme('p', 'keskel', '', '', 'посередині'),
  Lexeme('p', 'sees', '', '', 'усередині'),
  Lexeme('p', 'mööda', '', '', 'уздовж, по'),
  // ---------------- Служебные слова ----------------
  Lexeme('x', 'mina', 'ma', '', 'я'),
  Lexeme('x', 'sina', 'sa', '', 'ти'),
  Lexeme('x', 'tema', 'ta', '', 'він / вона'),
  Lexeme('x', 'meie', 'me', '', 'ми'),
  Lexeme('x', 'teie', 'te', '', 'ви'),
  Lexeme('x', 'nemad', 'nad', '', 'вони'),
  Lexeme('x', 'minu', 'mu', '', 'мій'),
  Lexeme('x', 'sinu', 'su', '', 'твій'),
  Lexeme('x', 'oma', '', '', 'свій'),
  Lexeme('x', 'mul', '', '', 'у мене'),
  Lexeme('x', 'mulle', '', '', 'мені'),
  Lexeme('x', 'mind', '', '', 'мене'),
  Lexeme('x', 'meil', '', '', 'у нас'),
  Lexeme('x', 'tal', '', '', 'у нього / у неї'),
  Lexeme('x', 'talle', '', '', 'йому / їй'),
  Lexeme('x', 'neil', '', '', 'у них'),
  Lexeme('n', 'see', 'selle', 'seda', 'це, цей'),
  Lexeme('n', 'need', 'nende', 'neid', 'ці'),
  Lexeme('x', 'ja', '', '', 'і'),
  Lexeme('x', 'ning', '', '', 'та, і'),
  Lexeme('x', 'aga', '', '', 'але'),
  Lexeme('x', 'või', '', '', 'або'),
  Lexeme('x', 'et', '', '', 'що, щоб'),
  Lexeme('x', 'sest', '', '', 'тому що'),
  Lexeme('x', 'kui', '', '', 'як, якщо, коли'),
  Lexeme('x', 'kuid', '', '', 'проте'),
  Lexeme('x', 'kas', '', '', '(питальна частка)'),
  Lexeme('x', 'ei', '', '', 'ні, не'),
  Lexeme('x', 'jah', '', '', 'так'),
  Lexeme('x', 'ka', '', '', 'також'),
  Lexeme('n', 'kes', 'kelle', 'keda', 'хто'),
  Lexeme('n', 'mis', 'mille', 'mida', 'що'),
  Lexeme('x', 'kus', '', '', 'де'),
  Lexeme('x', 'kuhu', '', '', 'куди'),
  Lexeme('x', 'kust', '', '', 'звідки'),
  Lexeme('x', 'siin', '', '', 'тут'),
  Lexeme('x', 'seal', '', '', 'там'),
  Lexeme('x', 'sinna', '', '', 'туди'),
  Lexeme('x', 'siia', '', '', 'сюди'),
  Lexeme('x', 'nüüd', '', '', 'тепер'),
  Lexeme('x', 'juba', '', '', 'вже'),
  Lexeme('x', 'veel', '', '', 'ще'),
  Lexeme('x', 'alati', '', '', 'завжди'),
  Lexeme('x', 'tihti', '', '', 'часто'),
  Lexeme('x', 'mõnikord', '', '', 'іноді'),
  Lexeme('x', 'tavaliselt', '', '', 'зазвичай'),
  Lexeme('x', 'umbes', '', '', 'приблизно'),
  Lexeme('x', 'palju', '', '', 'багато'),
  Lexeme('x', 'natuke', '', '', 'трохи'),
  Lexeme('x', 'väga', '', '', 'дуже'),
  Lexeme('x', 'kõik', '', '', 'все, всі'),
  Lexeme('x', 'iga', '', '', 'кожен'),
  Lexeme('x', 'igal', '', '', 'кожного'),
  Lexeme('x', 'hästi', '', '', 'добре'),
  Lexeme('x', 'kohe', '', '', 'одразу'),
  Lexeme('x', 'siis', '', '', 'тоді, потім'),
  Lexeme('x', 'ainult', '', '', 'лише'),
  Lexeme('x', 'koos', '', '', 'разом'),
  Lexeme('x', 'ilma', '', '', 'без'),
  Lexeme('x', 'täna', '', '', 'сьогодні'),
  Lexeme('x', 'homme', '', '', 'завтра'),
  Lexeme('x', 'vara', '', '', 'рано'),
  Lexeme('x', 'praegu', '', '', 'зараз'),
  Lexeme('x', 'lõpuks', '', '', 'нарешті'),
  Lexeme('x', 'edasi', '', '', 'далі'),
  Lexeme('x', 'tagasi', '', '', 'назад'),
  Lexeme('x', 'üles', '', '', 'вгору'),
  Lexeme('x', 'välja', '', '', 'назовні'),
  Lexeme('x', 'olemas', '', '', 'наявний, є'),
  Lexeme('x', 'avatud', '', '', 'відчинений'),
  Lexeme('x', 'kinni', '', '', 'зачинений'),
  Lexeme('x', 'täis', '', '', 'повний'),
  Lexeme('x', 'tasuta', '', '', 'безкоштовно'),
  Lexeme('x', 'möbleeritud', '', '', 'мебльований'),
  Lexeme('x', 'renoveeritud', '', '', 'відремонтований'),
  Lexeme('x', 'klaasitud', '', '', 'засклений'),
  Lexeme('x', 'organiseeritud', '', '', 'організований'),
  Lexeme('x', 'pärit', '', '', 'родом'),
  Lexeme('x', 'vaja', '', '', 'потрібно'),
  Lexeme('x', 'võib-olla', '', '', 'можливо'),
  Lexeme('x', 'ometi', '', '', 'все ж'),
  Lexeme('x', 'samuti', '', '', 'так само'),
  Lexeme('x', 'seejärel', '', '', 'після цього'),
  Lexeme('x', 'sellepärast', '', '', 'тому'),
  Lexeme('x', 'nagu', '', '', 'як, наче'),
  Lexeme('x', 'oli', '', '', 'був / була'),
  Lexeme('x', 'on', '', '', 'є (3-тя особа від olema)'),

  // ---------------- Дополнение: кухня ----------------
  Lexeme('n', 'valamu', 'valamu', 'valamut', 'мийка'),
  Lexeme('n', 'röster', 'röstri', 'röstrit', 'тостер'),
  Lexeme('n', 'veekann', 'veekannu', 'veekannu', 'електрочайник'),
  Lexeme('n', 'pann', 'panni', 'panni', 'сковорода'),
  Lexeme('n', 'pott', 'poti', 'potti', 'каструля'),
  Lexeme('n', 'nuga', 'noa', 'nuga', 'ніж'),
  Lexeme('n', 'kahvel', 'kahvli', 'kahvlit', 'виделка'),
  Lexeme('n', 'lusikas', 'lusika', 'lusikat', 'ложка'),
  Lexeme('n', 'kauss', 'kausi', 'kaussi', 'миска'),
  Lexeme('n', 'taldrik', 'taldriku', 'taldrikut', 'тарілка', 'taldrikuid'),
  Lexeme('n', 'käsn', 'käsna', 'käsna', 'губка'),
  Lexeme('n', 'nõudepesuvahend', 'nõudepesuvahendi', 'nõudepesuvahendit', 'засіб для миття посуду'),
  Lexeme('n', 'kann', 'kannu', 'kannu', 'глечик'),
  Lexeme('n', 'soolatoos', 'soolatoosi', 'soolatoosi', 'сільничка'),
  Lexeme('n', 'suhkrutoos', 'suhkrutoosi', 'suhkrutoosi', 'цукорниця'),
  Lexeme('n', 'suhkur', 'suhkru', 'suhkrut', 'цукор'),
  Lexeme('n', 'koristus', 'koristuse', 'koristust', 'прибирання'),
  Lexeme('n', 'kruvikeeraja', 'kruvikeeraja', 'kruvikeerajat', 'викрутка'),
  Lexeme('n', 'puiestee', 'puiestee', 'puiesteed', 'алея'),
  Lexeme('n', 'riidepood', 'riidepoe', 'riidepoodi', 'магазин одягу'),
  Lexeme('n', 'kõrva-nina-kurguarst', 'kõrva-nina-kurguarsti',
      'kõrva-nina-kurguarsti', 'ЛОР-лікар'),
  Lexeme('n', 'limonaad', 'limonaadi', 'limonaadi', 'лимонад'),
  // ---------------- Дополнение: существительные ----------------
  Lexeme('n', 'matk', 'matka', 'matka', 'похід'),
  Lexeme('n', 'kiri', 'kirja', 'kirja', 'лист'),
  Lexeme('n', 'pudel', 'pudeli', 'pudelit', 'пляшка'),
  Lexeme('n', 'vahe', 'vahe', 'vahet', 'різниця'),
  Lexeme('n', 'elu', 'elu', 'elu', 'життя'),
  Lexeme('n', 'mõte', 'mõtte', 'mõtet', 'думка'),
  Lexeme('n', 'mõtlemine', 'mõtlemise', 'mõtlemist', 'мислення'),
  Lexeme('n', 'tükk', 'tüki', 'tükki', 'шматок; штука'),
  Lexeme('n', 'tass', 'tassi', 'tassi', 'чашка'),
  Lexeme('n', 'vein', 'veini', 'veini', 'вино'),
  Lexeme('n', 'viinamari', 'viinamarja', 'viinamarja', 'виноградина', 'viinamarju'),
  Lexeme('n', 'kruasaan', 'kruasaani', 'kruasaani', 'круасан'),
  Lexeme('n', 'vanus', 'vanuse', 'vanust', 'вік'),
  Lexeme('n', 'lemmik', 'lemmiku', 'lemmikut', 'улюбленець', 'lemmikuid'),
  Lexeme('n', 'keskus', 'keskuse', 'keskust', 'центр'),
  Lexeme('n', 'spordikeskus', 'spordikeskuse', 'spordikeskust', 'спортивний центр'),
  Lexeme('n', 'arvutus', 'arvutuse', 'arvutust', 'розрахунок'),
  Lexeme('n', 'kaup', 'kauba', 'kaupa', 'товар'),
  Lexeme('n', 'tarne', 'tarne', 'tarnet', 'доставка'),
  Lexeme('n', 'soodustus', 'soodustuse', 'soodustust', 'знижка'),
  Lexeme('n', 'pakk', 'paki', 'pakki', 'посилка'),
  Lexeme('n', 'sõnum', 'sõnumi', 'sõnumit', 'повідомлення'),
  Lexeme('n', 'aadress', 'aadressi', 'aadressi', 'адреса'),
  Lexeme('n', 'kontakt', 'kontakti', 'kontakti', 'контакт'),
  Lexeme('n', 'telefon', 'telefoni', 'telefoni', 'телефон'),
  Lexeme('n', 'viiul', 'viiuli', 'viiulit', 'скрипка'),
  Lexeme('n', 'kabe', 'kabe', 'kabet', 'шашки'),
  Lexeme('n', 'pesu', 'pesu', 'pesu', 'білизна; прання'),
  Lexeme('n', 'lõuna', 'lõuna', 'lõunat', 'обід; південь'),
  Lexeme('n', 'rula', 'rula', 'rulat', 'скейтборд'),
  Lexeme('n', 'tolmuimeja', 'tolmuimeja', 'tolmuimejat', 'пилосос'),
  Lexeme('n', 'pikendusjuhe', 'pikendusjuhtme', 'pikendusjuhet', 'подовжувач'),
  Lexeme('n', 'mutrivõti', 'mutrivõtme', 'mutrivõtit', 'гайковий ключ'),
  Lexeme('n', 'pilt', 'pildi', 'pilti', 'зображення, фото', 'pilte'),
  Lexeme('n', 'hammas', 'hamba', 'hammast', 'зуб', 'hambaid'),
  Lexeme('n', 'kodutöö', 'kodutöö', 'kodutööd', 'домашнє завдання', 'kodutöid'),
  Lexeme('n', 'hetk', 'hetke', 'hetke', 'мить'),
  Lexeme('n', 'ese', 'eseme', 'eset', 'предмет', 'esemeid'),
  Lexeme('n', 'kilo', 'kilo', 'kilo', 'кілограм'),
  Lexeme('n', 'info', 'info', 'infot', 'інформація'),
  Lexeme('n', 'hoov', 'hoovi', 'hoovi', 'двір'),
  Lexeme('n', 'rõõm', 'rõõmu', 'rõõmu', 'радість'),
  Lexeme('n', 'hääl', 'hääle', 'häält', 'голос'),
  Lexeme('n', 'kord', 'korra', 'korda', 'раз; порядок'),
  Lexeme('n', 'kaugus', 'kauguse', 'kaugust', 'відстань'),
  Lexeme('n', 'suvi', 'suve', 'suve', 'літо'),
  Lexeme('n', 'talv', 'talve', 'talve', 'зима'),
  Lexeme('n', 'märts', 'märtsi', 'märtsi', 'березень'),
  Lexeme('n', 'aprill', 'aprilli', 'aprilli', 'квітень'),
  Lexeme('n', 'tulevik', 'tuleviku', 'tulevikku', 'майбутнє'),
  Lexeme('n', 'algus', 'alguse', 'algust', 'початок'),
  Lexeme('n', 'lõpp', 'lõpu', 'lõppu', 'кінець'),
  Lexeme('n', 'maa', 'maa', 'maad', 'земля; село (maal — у селі)'),
  Lexeme('n', 'asutus', 'asutuse', 'asutust', 'заклад', 'asutusi'),
  Lexeme('n', 'unistus', 'unistuse', 'unistust', 'мрія', 'unistusi'),
  Lexeme('n', 'kanarbik', 'kanarbiku', 'kanarbikku', 'верес'),
  Lexeme('n', 'esmaspäev', 'esmaspäeva', 'esmaspäeva', 'понеділок'),
  Lexeme('n', 'teisipäev', 'teisipäeva', 'teisipäeva', 'вівторок'),
  Lexeme('n', 'kolmapäev', 'kolmapäeva', 'kolmapäeva', 'середа'),
  Lexeme('n', 'neljapäev', 'neljapäeva', 'neljapäeva', 'четвер'),
  Lexeme('n', 'reede', 'reede', 'reedet', 'п’ятниця'),
  Lexeme('n', 'laupäev', 'laupäeva', 'laupäeva', 'субота'),
  Lexeme('n', 'pühapäev', 'pühapäeva', 'pühapäeva', 'неділя'),
  // ---------------- Дополнение: топонимы ----------------
  Lexeme('n', 'eesti', 'eesti', 'eestit', 'Естонія; естонський'),
  Lexeme('n', 'ukraina', 'ukraina', 'ukrainat', 'Україна; український'),
  Lexeme('n', 'narva', 'narva', 'narvat', 'Нарва (місто)'),
  Lexeme('n', 'maardu', 'maardu', 'maardut', 'Маарду (місто)'),
  Lexeme('n', 'pärnu', 'pärnu', 'pärnut', 'Пярну (місто)'),
  Lexeme('n', 'keila', 'keila', 'keilat', 'Кейла (місто)'),
  Lexeme('n', 'jõhvi', 'jõhvi', 'jõhvit', 'Йихві (місто)'),
  Lexeme('n', 'odessa', 'odessa', 'odessat', 'Одеса'),
  Lexeme('n', 'berdjansk', 'berdjanski', 'berdjanskit', 'Бердянськ'),
  Lexeme('n', 'kiiev', 'kiievi', 'kiievit', 'Київ'),
  Lexeme('n', 'nõmme', 'nõmme', 'nõmmet', 'Нимме (район Таллінна)'),
  Lexeme('n', 'tallinn', 'tallinna', 'tallinnat', 'Таллінн'),
  // ---------------- Дополнение: прилагательные ----------------
  Lexeme('a', 'armas', 'armsa', 'armsat', 'милий'),
  Lexeme('a', 'terve', 'terve', 'tervet', 'здоровий; цілий'),
  Lexeme('a', 'ümmargune', 'ümmarguse', 'ümmargust', 'круглий'),
  Lexeme('a', 'järgmine', 'järgmise', 'järgmist', 'наступний'),
  Lexeme('a', 'eelmine', 'eelmise', 'eelmist', 'попередній'),
  Lexeme('a', 'vajalik', 'vajaliku', 'vajalikku', 'потрібний'),
  Lexeme('a', 'tähtis', 'tähtsa', 'tähtsat', 'важливий'),
  Lexeme('a', 'mõni', 'mõne', 'mõnda', 'деякий, якийсь'),
  Lexeme('a', 'milline', 'millise', 'millist', 'який'),
  Lexeme('a', 'mitmes', 'mitmenda', 'mitmendat', 'котрий (за порядком)'),
  Lexeme('a', 'mitu', 'mitme', 'mitut', 'скільки'),
  Lexeme('a', 'kumb', 'kumma', 'kumba', 'котрий з двох'),
  Lexeme('a', 'mõnus', 'mõnusa', 'mõnusat', 'приємний'),
  Lexeme('a', 'lahke', 'lahke', 'lahket', 'привітний, добрий'),
  Lexeme('a', 'julge', 'julge', 'julget', 'сміливий'),
  Lexeme('a', 'loomulik', 'loomuliku', 'loomulikku', 'природний'),
  Lexeme('a', 'rõõmus', 'rõõmsa', 'rõõmsat', 'радісний'),
  Lexeme('a', 'erinev', 'erineva', 'erinevat', 'різний', 'erinevaid'),
  Lexeme('a', 'elav', 'elava', 'elavat', 'жвавий', 'elavaid'),
  Lexeme('a', 'sama', 'sama', 'sama', 'той самий'),
  Lexeme('a', 'aastane', 'aastase', 'aastast', '-річний (kolmekümneaastane — тридцятирічний)'),
  Lexeme('a', 'kakskümmend', 'kahekümne', 'kakskümmend', 'двадцять'),
  Lexeme('a', 'kolmkümmend', 'kolmekümne', 'kolmkümmend', 'тридцять'),
  Lexeme('a', 'nelikümmend', 'neljakümne', 'nelikümmend', 'сорок'),
  Lexeme('a', 'viiskümmend', 'viiekümne', 'viiskümmend', 'п’ятдесят'),
  Lexeme('a', 'kuuskümmend', 'kuuekümne', 'kuuskümmend', 'шістдесят'),
  Lexeme('a', 'seitsekümmend', 'seitsmekümne', 'seitsekümmend', 'сімдесят'),
  Lexeme('a', 'kaheksakümmend', 'kaheksakümne', 'kaheksakümmend', 'вісімдесят'),
  Lexeme('a', 'üheksakümmend', 'üheksakümne', 'üheksakümmend', 'дев’яносто'),
  Lexeme('a', 'kolmteist', 'kolmeteistkümne', 'kolmteist', 'тринадцять'),
  Lexeme('a', 'kaksteist', 'kaheteistkümne', 'kaksteist', 'дванадцять'),
  Lexeme('a', 'viisteist', 'viieteistkümne', 'viisteist', 'п’ятнадцять'),
  Lexeme('a', 'kaheksateist', 'kaheksateistkümne', 'kaheksateist', 'вісімнадцять'),
  // ---------------- Дополнение: глаголы ----------------
  Lexeme('v', 'võima', 'võida', 'või', 'могти'),
  Lexeme('v', 'kõlama', 'kõlada', 'kõla', 'звучати'),
  Lexeme('v', 'kartma', 'karta', 'karda', 'боятися'),
  Lexeme('v', 'laskma', 'lasta', 'lase', 'дозволяти, пускати'),
  Lexeme('v', 'jääma', 'jääda', 'jää', 'залишатися'),
  Lexeme('v', 'saabuma', 'saabuda', 'saabu', 'прибувати'),
  Lexeme('v', 'saatma', 'saata', 'saada', 'надсилати'),
  Lexeme('v', 'tagastama', 'tagastada', 'tagasta', 'повертати'),
  Lexeme('v', 'sõbrustama', 'sõbrustada', 'sõbrusta', 'дружити'),
  Lexeme('v', 'alustama', 'alustada', 'alusta', 'починати'),
  Lexeme('v', 'toimuma', 'toimuda', 'toimu', 'відбуватися'),
  Lexeme('v', 'kirjeldama', 'kirjeldada', 'kirjelda', 'описувати'),
  Lexeme('v', 'tähendama', 'tähendada', 'tähenda', 'означати'),
  Lexeme('v', 'arendama', 'arendada', 'arenda', 'розвивати'),
  Lexeme('v', 'liigutama', 'liigutada', 'liiguta', 'рухати(ся)'),
  Lexeme('v', 'aurama', 'aurata', 'aura', 'парувати'),
  Lexeme('v', 'hooldama', 'hooldada', 'hoolda', 'доглядати'),
  Lexeme('v', 'maitsema', 'maitseda', 'maitse', 'смакувати'),
  Lexeme('v', 'tulema', 'tulla', 'tule', 'приходити'),
  // ---------------- Дополнение: служебные и приветствия ----------------
  Lexeme('x', 'tere', '', '', 'привіт, добрий день'),
  Lexeme('x', 'tervist', '', '', 'вітаю, добрий день'),
  Lexeme('x', 'aitäh', '', '', 'дякую'),
  Lexeme('x', 'palun', '', '', 'будь ласка; прошу'),
  Lexeme('x', 'vabandust', '', '', 'вибачте'),
  Lexeme('x', 'nägemist', '', '', 'до побачення'),
  Lexeme('x', 'halloo', '', '', 'алло'),
  Lexeme('x', 'ohoo', '', '', 'ого'),
  Lexeme('x', 'noh', '', '', 'ну'),
  Lexeme('x', 'ju', '', '', 'же, адже'),
  Lexeme('x', 'nii', '', '', 'так, настільки'),
  Lexeme('x', 'sisse', '', '', 'всередину'),
  Lexeme('x', 'kokku', '', '', 'разом, докупи'),
  Lexeme('x', 'aru', '', '', 'saan aru — я розумію'),
  Lexeme('x', 'kaasa', '', '', 'із собою'),
  Lexeme('x', 'alles', '', '', 'ще, лишається'),
  Lexeme('x', 'näiteks', '', '', 'наприклад'),
  Lexeme('x', 'seega', '', '', 'отже'),
  Lexeme('x', 'eriti', '', '', 'особливо'),
  Lexeme('x', 'kaua', '', '', 'довго'),
  Lexeme('x', 'rohkem', '', '', 'більше'),
  Lexeme('x', 'vähem', '', '', 'менше'),
  Lexeme('x', 'miks', '', '', 'чому'),
  Lexeme('x', 'millal', '', '', 'коли'),
  Lexeme('x', 'kuidas', '', '', 'як'),
  Lexeme('x', 'end', 'enda', 'ennast', 'себе'),
  Lexeme('x', 'endale', '', '', 'собі'),
  Lexeme('x', 'rahul', '', '', 'задоволений (olen rahul)'),
  Lexeme('x', 'nõus', '', '', 'згоден (olen nõus)'),
  Lexeme('x', 'korras', '', '', 'у порядку'),
  Lexeme('x', 'õigesti', '', '', 'правильно'),
  Lexeme('x', 'täiesti', '', '', 'цілком'),
  Lexeme('x', 'päris', '', '', 'досить; справжній'),
  Lexeme('x', 'kaugel', '', '', 'далеко'),
  Lexeme('x', 'midagi', '', '', 'щось; нічого (із запереченням)'),
  Lexeme('x', 'keegi', '', '', 'хтось'),
  Lexeme('x', 'abielus', '', '', 'одружений / заміжня'),
  Lexeme('x', 'lubatud', '', '', 'дозволено'),
  Lexeme('x', 'õhtuti', '', '', 'вечорами'),
  Lexeme('x', 'hommikuti', '', '', 'вранці (щоранку)'),
  Lexeme('x', 'sul', '', '', 'у тебе'),
  Lexeme('x', 'sulle', '', '', 'тобі'),
  Lexeme('x', 'sind', '', '', 'тебе'),
  Lexeme('x', 'teil', '', '', 'у вас'),
  Lexeme('x', 'teile', '', '', 'вам'),
  Lexeme('x', 'teid', '', '', 'вас'),
  Lexeme('x', 'meile', '', '', 'нам'),
  Lexeme('x', 'meid', '', '', 'нас'),
  Lexeme('x', 'minul', '', '', 'у мене'),
  Lexeme('x', 'sinul', '', '', 'у тебе'),
  Lexeme('x', 'teda', '', '', 'його / її'),
  Lexeme('x', 'temaga', '', '', 'з ним / з нею'),
  Lexeme('x', 'minuga', '', '', 'зі мною'),
  Lexeme('x', 'sinuga', '', '', 'з тобою'),
  Lexeme('x', 'meiega', '', '', 'з нами'),
  Lexeme('x', 'teiega', '', '', 'з вами'),
  Lexeme('x', 'pluss', '', '', 'плюс'),
  Lexeme('x', 'miinus', '', '', 'мінус'),
  Lexeme('x', 'wc', '', '', 'туалет'),
  Lexeme('x', 'nimetav', '', '', 'називний відмінок (kes? mis?)'),
  Lexeme('x', 'omastav', '', '', 'родовий відмінок (kelle? mille?)'),
  Lexeme('x', 'osastav', '', '', 'частковий відмінок (keda? mida?)'),
  Lexeme('x', 'seestütlev', '', '', 'відмінок «з чого» (kust?)'),
  Lexeme('x', 'sisseütlev', '', '', 'відмінок «у що» (kuhu?)'),
  Lexeme('x', 'seesütlev', '', '', 'відмінок «у чому» (kus?)'),
  Lexeme('x', 'saav', '', '', 'відмінок «ким стає» (kelleks?)'),
  Lexeme('x', 'kaasaütlev', '', '', 'відмінок «з ким» (kellega?)'),
  Lexeme('p', 'jaoks', '', '', 'для (кого/чого)'),
  Lexeme('p', 'jooksul', '', '', 'протягом'),
  Lexeme('p', 'eest', '', '', 'за (щось) — aitäh abi eest'),
  Lexeme('p', 'järel', '', '', 'після, слідом'),

  Lexeme('n', 'õng', 'õnge', 'õnge', 'вудка'),
  Lexeme('n', 'ämber', 'ämbri', 'ämbrit', 'відро'),
  Lexeme('n', 'äär', 'ääre', 'äärt', 'край'),
  Lexeme('n', 'ülane', 'ülase', 'ülast', 'анемона (квітка)'),
  Lexeme('n', 'jää', 'jää', 'jääd', 'лід'),
  Lexeme('n', 'äike', 'äikese', 'äikest', 'гроза'),
  Lexeme('n', 'ööbik', 'ööbiku', 'ööbikut', 'соловей'),
  Lexeme('n', 'värv', 'värvi', 'värvi', 'колір'),
  Lexeme('n', 'doktor', 'doktori', 'doktorit', 'доктор'),
  Lexeme('n', 'kala', 'kala', 'kala', 'риба', 'kalu'),
  Lexeme('n', 'hoidmine', 'hoidmise', 'hoidmist', 'зберігання'),
  Lexeme('n', 'paar', 'paari', 'paari', 'пара'),
  Lexeme('n', 'parkimine', 'parkimise', 'parkimist', 'паркування'),
  Lexeme('x', 'päriselt', '', '', 'назавжди, по-справжньому'),

  // ---------------- Уроки 21-30: глаголы ----------------
  Lexeme('v', 'tantsima', 'tantsida', 'tantsi', 'танцювати'),
  Lexeme('v', 'laulma', 'laulda', 'laula', 'співати'),
  Lexeme('v', 'avama', 'avada', 'ava', 'відкривати'),
  Lexeme('v', 'sulgema', 'sulgeda', 'sulge', 'закривати'),
  Lexeme('v', 'ehitama', 'ehitada', 'ehita', 'будувати'),
  Lexeme('v', 'parandama', 'parandada', 'paranda', 'ремонтувати'),
  Lexeme('v', 'projekteerima', 'projekteerida', 'projekteeri', 'проєктувати'),
  Lexeme('v', 'naerma', 'naerda', 'naera', 'сміятися'),
  Lexeme('v', 'katsuma', 'katsuda', 'katsu', 'торкатися'),
  Lexeme('v', 'imestama', 'imestada', 'imesta', 'дивуватися'),
  Lexeme('v', 'liikuma', 'liikuda', 'liigu', 'рухатися'),
  Lexeme('v', 'kõndima', 'kõndida', 'kõnni', 'крокувати, йти'),
  Lexeme('v', 'võrdlema', 'võrrelda', 'võrdle', 'порівнювати'),
  Lexeme('v', 'arvama', 'arvata', 'arva', 'вважати, думати'),
  Lexeme('v', 'kammima', 'kammida', 'kammi', 'розчісувати'),
  Lexeme('v', 'kiikuma', 'kiikuda', 'kiigu', 'гойдатися'),
  Lexeme('v', 'joonistama', 'joonistada', 'joonista', 'малювати'),
  Lexeme('v', 'kuduma', 'kududa', 'koo', 'в’язати'),
  Lexeme('v', 'reisima', 'reisida', 'reisi', 'подорожувати'),
  Lexeme('v', 'matkama', 'matkata', 'matka', 'ходити в похід'),
  Lexeme('v', 'keetma', 'keeta', 'keeda', 'варити'),
  Lexeme('v', 'tellima', 'tellida', 'telli', 'замовляти'),
  Lexeme('v', 'otsima', 'otsida', 'otsi', 'шукати'),
  Lexeme('v', 'unistama', 'unistada', 'unista', 'мріяти'),
  Lexeme('v', 'toetama', 'toetada', 'toeta', 'підтримувати'),
  Lexeme('v', 'veetma', 'veeta', 'veeda', 'проводити (час)'),
  Lexeme('v', 'külastama', 'külastada', 'külasta', 'відвідувати'),
  Lexeme('v', 'tõusma', 'tõusta', 'tõuse', 'вставати'),
  Lexeme('v', 'noogutama', 'noogutada', 'nooguta', 'кивати'),
  Lexeme('v', 'kiirustama', 'kiirustada', 'kiirusta', 'поспішати'),
  Lexeme('v', 'mööduma', 'mööduda', 'möödu', 'минати'),
  Lexeme('v', 'juhtuma', 'juhtuda', 'juhtu', 'ставатися'),
  Lexeme('v', 'kasutama', 'kasutada', 'kasuta', 'використовувати'),
  Lexeme('v', 'nägema', 'näha', 'näe', 'бачити'),

  // ---------------- Уроки 21-30: существительные ----------------
  Lexeme('n', 'tütar', 'tütre', 'tütart', 'донька'),
  Lexeme('n', 'tüdruk', 'tüdruku', 'tüdrukut', 'дівчина', 'tüdrukuid'),
  Lexeme('n', 'poiss', 'poisi', 'poissi', 'хлопець', 'poisse'),
  Lexeme('n', 'kivi', 'kivi', 'kivi', 'камінь'),
  Lexeme('n', 'karu', 'karu', 'karu', 'ведмідь'),
  Lexeme('n', 'rebane', 'rebase', 'rebast', 'лисиця'),
  Lexeme('n', 'hiir', 'hiire', 'hiirt', 'миша', 'hiiri'),
  Lexeme('n', 'hunt', 'hundi', 'hunti', 'вовк'),
  Lexeme('n', 'ilves', 'ilvese', 'ilvest', 'рись'),
  Lexeme('n', 'jänes', 'jänese', 'jänest', 'заєць'),
  Lexeme('n', 'siil', 'siili', 'siili', 'їжак'),
  Lexeme('n', 'öökull', 'öökulli', 'öökulli', 'сова'),
  Lexeme('n', 'kilpkonn', 'kilpkonna', 'kilpkonna', 'черепаха'),
  Lexeme('n', 'kobra', 'kobra', 'kobrat', 'кобра'),
  Lexeme('n', 'mesilane', 'mesilase', 'mesilast', 'бджола'),
  Lexeme('n', 'lõvi', 'lõvi', 'lõvit', 'лев; Лев (знак)'),
  Lexeme('n', 'giid', 'giidi', 'giidi', 'гід'),
  Lexeme('n', 'fotograaf', 'fotograafi', 'fotograafi', 'фотограф'),
  Lexeme('n', 'veevalaja', 'veevalaja', 'veevalajat', 'Водолій (знак)'),
  Lexeme('n', 'ehitaja', 'ehitaja', 'ehitajat', 'будівельник'),
  Lexeme('n', 'töötaja', 'töötaja', 'töötajat', 'працівник'),
  Lexeme('n', 'vanaisa', 'vanaisa', 'vanaisat', 'дідусь'),
  Lexeme('n', 'lapselaps', 'lapselapse', 'lapselast', 'онук / онука'),
  Lexeme('n', 'pluus', 'pluusi', 'pluusi', 'блуза'),
  Lexeme('n', 'põrandalamp', 'põrandalambi', 'põrandalampi', 'торшер'),
  Lexeme('n', 'aknalaud', 'aknalaua', 'aknalauda', 'підвіконня'),
  Lexeme('n', 'lillepott', 'lillepoti', 'lillepotti', 'горщик для квітів'),
  Lexeme('v', 'kandma', 'kanda', 'kanna', 'носити'),
  Lexeme('a', 'rõõmus', 'rõõmsa', 'rõõmsat', 'веселий, радісний'),
  Lexeme('x', 'üksteist', '', '', 'один одного'),
  Lexeme('x', 'vabaabielus', '', '', 'у цивільному шлюбі'),
  Lexeme('n', 'kleit', 'kleidi', 'kleiti', 'сукня'),
  Lexeme('n', 'särk', 'särgi', 'särki', 'сорочка'),
  Lexeme('n', 'teksased', 'teksaste', 'teksaseid', 'джинси'),
  Lexeme('n', 'teksapüksid', 'teksapükste', 'teksapükse', 'джинси'),
  Lexeme('n', 'logopeed', 'logopeedi', 'logopeedi', 'логопед'),
  Lexeme('n', 'abikaasa', 'abikaasa', 'abikaasat', 'чоловік / дружина'),
  Lexeme('n', 'haigla', 'haigla', 'haiglat', 'лікарня'),
  Lexeme('n', 'elektrik', 'elektriku', 'elektrikut', 'електрик'),
  Lexeme('n', 'insener', 'inseneri', 'inseneri', 'інженер'),
  Lexeme('n', 'juhe', 'juhtme', 'juhet', 'дріт, провід', 'juhtmeid'),
  Lexeme('n', 'masin', 'masina', 'masinat', 'машина, механізм', 'masinaid'),
  Lexeme('n', 'pinal', 'pinali', 'pinalit', 'пенал'),
  Lexeme('n', 'põõsas', 'põõsa', 'põõsast', 'кущ'),
  Lexeme('n', 'lagendik', 'lagendiku', 'lagendikku', 'галявина'),
  Lexeme('n', 'oja', 'oja', 'oja', 'струмок'),
  Lexeme('n', 'metsarada', 'metsaraja', 'metsarada', 'лісова стежка'),
  Lexeme('n', 'hiiglane', 'hiiglase', 'hiiglast', 'велетень'),
  Lexeme('n', 'oks', 'oksa', 'oksa', 'гілка', 'oksi'),
  Lexeme('n', 'vulin', 'vulina', 'vulinat', 'дзюрчання'),
  Lexeme('n', 'peatus', 'peatuse', 'peatust', 'зупинка'),
  Lexeme('n', 'tund', 'tunni', 'tundi', 'урок; година'),
  Lexeme('n', 'rühm', 'rühma', 'rühma', 'група'),
  Lexeme('n', 'meeskond', 'meeskonna', 'meeskonda', 'команда'),
  Lexeme('n', 'suveniir', 'suveniiri', 'suveniiri', 'сувенір', 'suveniire'),
  Lexeme('n', 'ananass', 'ananassi', 'ananassi', 'ананас'),
  Lexeme('n', 'apelsin', 'apelsini', 'apelsini', 'апельсин', 'apelsine'),
  Lexeme('n', 'vaas', 'vaasi', 'vaasi', 'ваза'),
  Lexeme('n', 'palm', 'palmi', 'palmi', 'пальма'),
  Lexeme('n', 'tagaplaan', 'tagaplaani', 'tagaplaani', 'задній план'),
  Lexeme('n', 'lamp', 'lambi', 'lampi', 'лампа', 'lampe'),
  Lexeme('n', 'kontor', 'kontori', 'kontorit', 'офіс', 'kontoreid'),
  Lexeme('n', 'ravim', 'ravimi', 'ravimit', 'ліки', 'ravimeid'),
  Lexeme('n', 'apteeker', 'apteekri', 'apteekrit', 'фармацевт'),
  Lexeme('n', 'buss', 'bussi', 'bussi', 'автобус'),
  Lexeme('n', 'bussijuht', 'bussijuhi', 'bussijuhti', 'водій автобуса'),
  Lexeme('n', 'beebi', 'beebi', 'beebit', 'немовля'),
  Lexeme('n', 'pall', 'palli', 'palli', 'м’яч'),
  Lexeme('n', 'saal', 'saali', 'saali', 'зал'),
  Lexeme('n', 'talu', 'talu', 'talu', 'ферма, хутір'),
  Lexeme('n', 'pilv', 'pilve', 'pilve', 'хмара', 'pilvi'),
  Lexeme('n', 'taevas', 'taeva', 'taevast', 'небо'),
  Lexeme('n', 'pink', 'pingi', 'pinki', 'лавка'),
  Lexeme('n', 'nokk', 'noka', 'nokka', 'дзьоб'),
  Lexeme('n', 'sulg', 'sule', 'sulge', 'перо', 'sulgi'),
  Lexeme('n', 'tiib', 'tiiva', 'tiiba', 'крило', 'tiibu'),
  Lexeme('n', 'saba', 'saba', 'saba', 'хвіст'),
  Lexeme('n', 'binokkel', 'binokli', 'binoklit', 'бінокль'),
  Lexeme('n', 'gloobus', 'gloobuse', 'gloobust', 'глобус'),
  Lexeme('n', 'võileib', 'võileiva', 'võileiba', 'бутерброд'),
  Lexeme('n', 'tahvel', 'tahvli', 'tahvlit', 'дошка'),
  Lexeme('n', 'vastus', 'vastuse', 'vastust', 'відповідь'),
  Lexeme('n', 'tekst', 'teksti', 'teksti', 'текст'),
  Lexeme('n', 'lause', 'lause', 'lauset', 'речення'),
  Lexeme('n', 'õpik', 'õpiku', 'õpikut', 'підручник', 'õpikuid'),
  Lexeme('n', 'sportlane', 'sportlase', 'sportlast', 'спортсмен'),
  Lexeme('n', 'tantsija', 'tantsija', 'tantsijat', 'танцюрист'),
  Lexeme('n', 'õppija', 'õppija', 'õppijat', 'учень, той, хто вчиться'),
  Lexeme('n', 'horoskoop', 'horoskoobi', 'horoskoopi', 'гороскоп'),
  Lexeme('n', 'kaksikud', 'kaksikute', 'kaksikuid', 'близнюки; Близнюки'),
  Lexeme('n', 'neitsi', 'neitsi', 'neitsit', 'Діва (знак)'),
  Lexeme('n', 'sõnn', 'sõnni', 'sõnni', 'Телець (знак)'),
  Lexeme('n', 'vähk', 'vähi', 'vähki', 'Рак (знак)'),
  Lexeme('n', 'kaalud', 'kaalude', 'kaalusid', 'Терези (знак)'),
  Lexeme('n', 'ambur', 'amburi', 'amburit', 'Стрілець (знак)'),
  Lexeme('n', 'kaljukits', 'kaljukitse', 'kaljukitse', 'Козоріг (знак)'),
  Lexeme('n', 'skorpion', 'skorpioni', 'skorpioni', 'Скорпіон (знак)'),
  Lexeme('n', 'jäär', 'jäära', 'jäära', 'Овен (знак); баран'),
  Lexeme('n', 'jaanuar', 'jaanuari', 'jaanuari', 'січень'),
  Lexeme('n', 'veebruar', 'veebruari', 'veebruari', 'лютий'),
  Lexeme('n', 'märts', 'märtsi', 'märtsi', 'березень'),
  Lexeme('n', 'aprill', 'aprilli', 'aprilli', 'квітень'),
  Lexeme('n', 'mai', 'mai', 'maid', 'травень'),
  Lexeme('n', 'juuni', 'juuni', 'juunit', 'червень'),
  Lexeme('n', 'juuli', 'juuli', 'juulit', 'липень'),
  Lexeme('n', 'august', 'augusti', 'augustit', 'серпень'),
  Lexeme('n', 'september', 'septembri', 'septembrit', 'вересень'),
  Lexeme('n', 'oktoober', 'oktoobri', 'oktoobrit', 'жовтень'),
  Lexeme('n', 'november', 'novembri', 'novembrit', 'листопад'),
  Lexeme('n', 'detsember', 'detsembri', 'detsembrit', 'грудень'),
  Lexeme('n', 'trenn', 'trenni', 'trenni', 'тренування'),
  Lexeme('n', 'piknik', 'pikniku', 'piknikku', 'пікнік'),
  Lexeme('n', 'multikas', 'multika', 'multikat', 'мультик', 'multikaid'),
  Lexeme('n', 'õhtusöök', 'õhtusöögi', 'õhtusööki', 'вечеря'),
  Lexeme('n', 'puuvili', 'puuvilja', 'puuvilja', 'фрукт', 'puuvilju'),
  Lexeme('n', 'lillepeenar', 'lillepeenra', 'lillepeenart', 'клумба'),
  Lexeme('n', 'tõde', 'tõe', 'tõtt', 'правда'),
  Lexeme('n', 'au', 'au', 'au', 'честь'),
  Lexeme('n', 'jutt', 'jutu', 'juttu', 'розмова, оповідь'),
  Lexeme('n', 'julgus', 'julguse', 'julgust', 'сміливість'),
  Lexeme('n', 'viisakus', 'viisakuse', 'viisakust', 'ввічливість'),
  Lexeme('n', 'lahkus', 'lahkuse', 'lahkust', 'доброта'),
  Lexeme('n', 'tarkus', 'tarkuse', 'tarkust', 'мудрість'),
  Lexeme('n', 'ilu', 'ilu', 'ilu', 'краса'),
  Lexeme('n', 'rahu', 'rahu', 'rahu', 'спокій, мир'),
  Lexeme('n', 'õnn', 'õnne', 'õnne', 'щастя'),
  Lexeme('n', 'optimism', 'optimismi', 'optimismi', 'оптимізм'),
  Lexeme('n', 'sport', 'spordi', 'sporti', 'спорт'),
  Lexeme('n', 'omand', 'omandi', 'omandit', 'власність'),
  Lexeme('n', 'paus', 'pausi', 'pausi', 'пауза'),
  Lexeme('n', 'tangid', 'tangide', 'tange', 'плоскогубці'),
  Lexeme('n', 'kiik', 'kiige', 'kiike', 'гойдалка'),
  Lexeme('n', 'sõit', 'sõidu', 'sõitu', 'поїздка'),
  Lexeme('n', 'metall', 'metalli', 'metalli', 'метал'),
  Lexeme('n', 'tuul', 'tuule', 'tuult', 'вітер'),
  Lexeme('n', 'Soome', 'Soome', 'Soomet', 'Фінляндія'),
  Lexeme('n', 'soomlane', 'soomlase', 'soomlast', 'фін'),
  Lexeme('n', 'koor', 'koori', 'koori', 'хор'),
  Lexeme('n', 'dokument', 'dokumendi', 'dokumenti', 'документ', 'dokumente'),
  Lexeme('n', 'peremees', 'peremehe', 'peremeest', 'господар'),
  Lexeme('n', 'seeme', 'seemne', 'seemet', 'насінина', 'seemneid'),
  Lexeme('n', 'seemned', 'seemnete', 'seemneid', 'насіння'),
  Lexeme('n', 'medõde', 'medõe', 'medõde', 'медсестра'),
  Lexeme('n', 'raamatupidaja', 'raamatupidaja', 'raamatupidajat', 'бухгалтер'),
  Lexeme('n', 'koolipoiss', 'koolipoisi', 'koolipoissi', 'школяр'),
  Lexeme('n', 'koolilaps', 'koolilapse', 'koolilast', 'школярка, учениця'),
  Lexeme('n', 'lasteaialaps', 'lasteaialapse', 'lasteaialast',
      'дитина з садочка'),
  Lexeme('n', 'lemmikloom', 'lemmiklooma', 'lemmiklooma',
      'домашній улюбленець'),
  Lexeme('n', 'puur', 'puuri', 'puuri', 'клітка'),
  Lexeme('n', 'hääl', 'hääle', 'häält', 'голос'),
  Lexeme('n', 'kook', 'koogi', 'kooki', 'тістечко, пиріг'),
  Lexeme('n', 'toit', 'toidu', 'toitu', 'їжа, страва', 'toite'),

  // ---------------- Уроки 21-30: прилагательные ----------------
  Lexeme('a', 'tark', 'targa', 'tarka', 'розумний'),
  Lexeme('a', 'tugev', 'tugeva', 'tugevat', 'сильний'),
  Lexeme('a', 'kurb', 'kurva', 'kurba', 'сумний'),
  Lexeme('a', 'halb', 'halva', 'halba', 'поганий'),
  Lexeme('a', 'kallis', 'kalli', 'kallist', 'дорогий'),
  Lexeme('a', 'lühike', 'lühikese', 'lühikest', 'короткий'),
  Lexeme('a', 'kaunis', 'kauni', 'kaunist', 'красивий'),
  Lexeme('a', 'aeglane', 'aeglase', 'aeglast', 'повільний'),
  Lexeme('a', 'kaval', 'kavala', 'kavalat', 'хитрий'),
  Lexeme('a', 'nutikas', 'nutika', 'nutikat', 'кмітливий'),
  Lexeme('a', 'vapper', 'vapra', 'vaprat', 'відважний'),
  Lexeme('a', 'paindlik', 'paindliku', 'paindlikku', 'гнучкий'),
  Lexeme('a', 'karvane', 'karvase', 'karvast', 'пухнастий'),
  Lexeme('a', 'okkaline', 'okkalise', 'okkalist', 'колючий'),
  Lexeme('a', 'öine', 'öise', 'öist', 'нічний'),
  Lexeme('a', 'graatsiline', 'graatsilise', 'graatsilist', 'граційний'),
  Lexeme('a', 'massiivne', 'massiivse', 'massiivset', 'масивний'),
  Lexeme('a', 'mürgine', 'mürgise', 'mürgist', 'отруйний'),
  Lexeme('a', 'kasulik', 'kasuliku', 'kasulikku', 'корисний'),
  Lexeme('a', 'kuri', 'kurja', 'kurja', 'злий'),
  Lexeme('a', 'aktiivne', 'aktiivse', 'aktiivset', 'активний'),
  Lexeme('a', 'sportlik', 'sportliku', 'sportlikku', 'спортивний'),
  Lexeme('a', 'südamlik', 'südamliku', 'südamlikku', 'щирий'),
  Lexeme('a', 'seltsiv', 'seltsiva', 'seltsivat', 'товариський'),
  Lexeme('a', 'optimistlik', 'optimistliku', 'optimistlikku',
      'оптимістичний'),
  Lexeme('a', 'pessimistlik', 'pessimistliku', 'pessimistlikku',
      'песимістичний'),
  Lexeme('a', 'emotsionaalne', 'emotsionaalse', 'emotsionaalset',
      'емоційний'),
  Lexeme('a', 'korralik', 'korraliku', 'korralikku', 'охайний'),
  Lexeme('a', 'hooliv', 'hooliva', 'hoolivat', 'турботливий'),
  Lexeme('a', 'energiline', 'energilise', 'energilist', 'енергійний'),
  Lexeme('a', 'loov', 'loova', 'loovat', 'творчий'),
  Lexeme('a', 'unistav', 'unistava', 'unistavat', 'мрійливий'),
  Lexeme('a', 'tasakaalukas', 'tasakaaluka', 'tasakaalukat',
      'врівноважений'),
  Lexeme('a', 'iseseisev', 'iseseisva', 'iseseisvat', 'самостійний'),
  Lexeme('a', 'otsekohene', 'otsekohese', 'otsekohest', 'прямолінійний'),
  Lexeme('a', 'kannatlik', 'kannatliku', 'kannatlikku', 'терплячий'),
  Lexeme('a', 'aus', 'ausa', 'ausat', 'чесний'),
  Lexeme('a', 'jutukas', 'jutuka', 'jutukat', 'балакучий'),
  Lexeme('a', 'lõbus', 'lõbusa', 'lõbusat', 'веселий'),
  Lexeme('a', 'tubli', 'tubli', 'tublit', 'старанний, молодець'),
  Lexeme('a', 'usin', 'usina', 'usinat', 'старанний'),
  Lexeme('a', 'tavaline', 'tavalise', 'tavalist', 'звичайний'),
  Lexeme('a', 'õnnelik', 'õnneliku', 'õnnelikku', 'щасливий'),
  Lexeme('a', 'mõistlik', 'mõistliku', 'mõistlikku', 'розумний'),
  Lexeme('a', 'seiklushimuline', 'seiklushimulise', 'seiklushimulist',
      'той, що любить пригоди'),
  Lexeme('a', 'rääkiv', 'rääkiva', 'rääkivat', 'той, що говорить'),
  Lexeme('a', 'maitsev', 'maitsva', 'maitsvat', 'смачний', 'maitsvaid'),
  Lexeme('a', 'värviline', 'värvilise', 'värvilist', 'різнокольоровий',
      'värvilisi'),
  Lexeme('a', 'eriline', 'erilise', 'erilist', 'особливий'),
  Lexeme('a', 'eilne', 'eilse', 'eilset', 'вчорашній'),
  Lexeme('a', 'kõva', 'kõva', 'kõva', 'гучний; твердий'),
  Lexeme('a', 'oluline', 'olulise', 'olulist', 'важливий'),
  Lexeme('a', 'turvaline', 'turvalise', 'turvalist', 'безпечний'),
  Lexeme('a', 'päikeseline', 'päikeselise', 'päikeselist', 'сонячний'),
  Lexeme('a', 'naljakas', 'naljaka', 'naljakat', 'смішний'),
  Lexeme('a', 'magus', 'magusa', 'magusat', 'солодкий'),
  Lexeme('a', 'pisike', 'pisikese', 'pisikest', 'малесенький'),
  Lexeme('a', 'kuulus', 'kuulsa', 'kuulsat', 'відомий'),
  Lexeme('a', 'kõrge', 'kõrge', 'kõrget', 'високий'),
  Lexeme('a', 'kahekorruseline', 'kahekorruselise', 'kahekorruselist',
      'двоповерховий'),
  Lexeme('a', 'väsinud', 'väsinud', 'väsinut', 'втомлений'),
  Lexeme('a', 'tähtis', 'tähtsa', 'tähtsat', 'важливий'),

  // ---------------- Уроки 21-30: служебные и послелоги ----------------
  Lexeme('p', 'järgi', '', '', 'за, згідно з'),
  Lexeme('x', 'kõige', '', '',
      'най- (частка найвищого ступеня): kõige suurem — найбільший'),
  Lexeme('x', 'siit', '', '', 'звідси'),
  Lexeme('x', 'sealt', '', '', 'звідти'),
  Lexeme('x', 'ära', '', '', 'геть; не (заборона): ära mine!'),
  Lexeme('x', 'ise', '', '', 'сам'),
  Lexeme('x', 'vist', '', '', 'мабуть'),
  Lexeme('x', 'üsna', '', '', 'доволі'),
  Lexeme('x', 'esmalt', '', '', 'спочатку'),
  Lexeme('x', 'isegi', '', '', 'навіть'),
  Lexeme('x', 'tõesti', '', '', 'справді'),
  Lexeme('x', 'enne', '', '', 'раніше, перед'),
  Lexeme('x', 'pärast', '', '', 'після'),
  Lexeme('x', 'ringi', '', '', 'навколо'),
  Lexeme('x', 'maha', '', '', 'вниз, додолу'),
  Lexeme('x', 'alla', '', '', 'вниз, під'),
  Lexeme('x', 'külla', '', '', 'в гості'),
  Lexeme('x', 'üle', '', '', 'понад, через'),
  Lexeme('x', 'üleval', '', '', 'нагорі, на ногах'),
  Lexeme('x', 'valjusti', '', '', 'голосно'),
  Lexeme('x', 'seljas', '', '', 'на собі (одяг)'),
  Lexeme('x', 'jalas', '', '', 'на ногах (взуття)'),
  Lexeme('x', 'minule', 'mulle', '', 'мені'),
  Lexeme('x', 'sinule', 'sulle', '', 'тобі'),
  Lexeme('x', 'neile', 'nendele', '', 'їм'),
];
